language: go
sudo: false
go_import_path: github.com/cjgiridhar/gin-geo
go:
  - 1.11.5
before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)